channels:
- conda-forge
dependencies:
- python=3.12.1
- pip<=23.2.1
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - psutil==6.0.0
  - scikit-learn==1.4.0
  - scipy==1.12.0
name: mlflow-env
